# Platform Configuration
platform:
  name: "Strategy Execution Platform"
  version: "0.1.0"
  environment: "development"

# Database Configuration
database:
  timescaledb:
    host: "localhost"
    port: 5432
    database: "platform_events"
    user: "platform"
    password: "platform_secure_pass"
    pool_size: 20
    max_overflow: 10

# Cache Configuration
cache:
  redis:
    host: "localhost"
    port: 6379
    db: 0
    max_connections: 50
    decode_responses: true

# Message Queue Configuration
messaging:
  nats:
    servers:
      - "nats://localhost:4222"
    max_reconnect_attempts: 10
    reconnect_time_wait: 2

# Distributed Computing Configuration
distributed:
  ray:
    head_address: "ray://localhost:10001"
    dashboard_url: "http://localhost:8265"
    num_cpus: 4
    num_gpus: 0
    object_store_memory: 2147483648 # 2GB

# Blockchain Configuration
blockchain:
  ethereum:
    mainnet:
      rpc_url: "https://eth-mainnet.g.alchemy.com/v2/YOUR_KEY"
      chain_id: 1
      block_confirmations: 12
    sepolia:
      rpc_url: "https://eth-sepolia.g.alchemy.com/v2/YOUR_KEY"
      chain_id: 11155111
      block_confirmations: 6
  arbitrum:
    mainnet:
      rpc_url: "https://arb-mainnet.g.alchemy.com/v2/YOUR_KEY"
      chain_id: 42161
      block_confirmations: 1
  base:
    mainnet:
      rpc_url: "https://mainnet.base.org"
      chain_id: 8453
      block_confirmations: 1

# Safe Configuration
safe:
  address: "0x0000000000000000000000000000000000000000"
  threshold: 2
  owners:
    - "0x0000000000000000000000000000000000000001"
    - "0x0000000000000000000000000000000000000002"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  rate_limit:
    requests_per_minute: 100

# Monitoring Configuration
monitoring:
  prometheus:
    enabled: true
    port: 9090
  logging:
    level: "INFO"
    format: "json"
    output: "stdout"

# Risk Configuration
risk:
  max_position_size: 100000
  max_daily_loss: 10000
  max_correlation: 0.8
  circuit_breaker_threshold: 0.15

# Execution Configuration
execution:
  max_concurrent_intents: 10
  solver_timeout_seconds: 5
  gas_price_multiplier: 1.2
  max_retries: 3
  retry_delay_seconds: 1
